name: Build Pelican Blog
run-name: Build this blog to output folder by @${{ github.actor }}
on: 
  [push, workflow_dispatch]
jobs:
  build:    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: csrw2.cs.ucl.ac.uk
          username: baichyin
          key: ${{ secrets.SSH_PASSWORD_BC }}
          port: 22
          script: whoami
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pelican[markdown]"

      - name: Build Website
        run: pelican content
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto built blog.
