name: Build Pelican Blog
run-name: Build this blog to content folder by @${{ github.actor }}
on: 
  push:
    branches:
      - main  # or whichever branch you are using
jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pelican[markdown]"

      - name: Build Website
        run: pelican content
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m 'Automatic update of Pelican content' || exit 0
          git push
