name: Build Pelican Blog
run-name: Build this blog to content folder by @${{ github.actor }}
on: 
  push:
    branches:
      - main  # or whichever branch you are using
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pelican[markdown]"

      - name: Build Website
        run: pelican content
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto built blog.
